//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetURLContent.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\\$\\(\"#myUniqueImg\"\\)\\.attr\\(\"src\",\")(\\b(?:(?:https?|ftp|file|[A-Za-z]+):\\/\\/|www" +
            "\\.|ftp\\.)(?:\\([-A-Z0-9+&@#\\/%=~_ |$?!:,.]*\\)|[-A-Z0-9+&@#\\/%=~_ |$?!:,.])*(?:\\([" +
            "-A-Z0-9+&@#\\/%=~_ |$?!:,.]*\\)|[A-Z0-9+&@#\\/%=~_ |$]))")]
        public string RegExPatternFirst {
            get {
                return ((string)(this["RegExPatternFirst"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\\b(?:(?:https?|ftp|file|[A-Za-z]+):\\/\\/|www\\.|ftp\\.)(?:\\([-A-Z0-9+&@#\\/%=~_ |$?!" +
            ":,.]*\\)|[-A-Z0-9+&@#\\/%=~_ |$?!:,.])*(?:\\([-A-Z0-9+&@#\\/%=~_ |$?!:,.]*\\)|[A-Z0-9" +
            "+&@#\\/%=~_ |$]))")]
        public string RegexPatternSecond {
            get {
                return ((string)(this["RegexPatternSecond"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<img id=\"photo\" src=\"(\\b(?:(?:https?|ftp|file|[A-Za-z]+):\\/\\/|www\\.|ftp\\.)(?:\\([-" +
            "A-Z0-9+&@#\\/%=~_ |$?!:,.]*\\)|[-A-Z0-9+&@#\\/%=~_ |$?!:,.])*(?:\\([-A-Z0-9+&@#\\/%=~" +
            "_ |$?!:,.]*\\)|[A-Z0-9+&@#\\/%=~_ |$]))")]
        public string RegExPatternFirstImagezilla {
            get {
                return ((string)(this["RegExPatternFirstImagezilla"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("href=\"(\\b(?:(?:https?|ftp|file|[A-Za-z]+):\\/\\/|www\\.|ftp\\.)(?:\\([-A-Z0-9+&@#\\/%=~" +
            "_ |$?!:,.]*\\)|[-A-Z0-9+&@#\\/%=~_ |$?!:,.])*(?:\\([-A-Z0-9+&@#\\/%=~_ |$?!:,.]*\\)|[" +
            "A-Z0-9+&@#\\/%=~_ |$]))")]
        public string RegExPatternFirstForLinks {
            get {
                return ((string)(this["RegExPatternFirstForLinks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("href=\'(\\b(?:(?:https?|ftp|file|[A-Za-z]+):\\/\\/|www\\.|ftp\\.)(?:\\([-A-Z0-9+&@#\\/%=~" +
            "_ |$?!:,.]*\\)|[-A-Z0-9+&@#\\/%=~_ |$?!:,.])*(?:\\([-A-Z0-9+&@#\\/%=~_ |$?!:,.]*\\)|[" +
            "A-Z0-9+&@#\\/%=~_ |$]))")]
        public string RegExPatternFirstForLinksGallerySense {
            get {
                return ((string)(this["RegExPatternFirstForLinksGallerySense"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tbTargetDownloadFolder {
            get {
                return ((string)(this["tbTargetDownloadFolder"]));
            }
            set {
                this["tbTargetDownloadFolder"] = value;
            }
        }
    }
}
